---
# file: roles/netdata/tasks/install.yml

- name: "Clone NetData"
  git:
    accept_hostkey: true
    repo: "https://github.com/firehol/netdata.git"
    dest: "/opt/netdata"
    force: yes
  register: netdata_clone
  notify:
    - "Restart NetData"

- name: "Install and configure NetData"
  shell: ./netdata-installer.sh --dont-wait
  args:
    chdir: /opt/netdata
  when: netdata_clone.changed

- name: "Copy additional files"
  copy:
    src: '{{ item.filename }}'
    dest: '{{ item.path }}/{{ item.filename }}'
  with_items:
    - filename: 'haproxy.chart.py'
      path: '/usr/libexec/netdata/python.d'
    - filename: 'haproxy.conf'
      path: '/etc/netdata/python.d'
  notify:
    - "Restart NetData"
