---
# file: roles/netdata/tasks/main.yml

- name: "NetData Role"
  set_fact: role_netdata_started=true
  tags: always

- block:

  - name: "Install required packages"
    apt:
      pkg={{ item }}
      state=installed
      update_cache=yes
    with_items:
      - zlib1g-dev
      - gcc
      - make
      - git
      - autoconf
      - autogen
      - automake
      - pkg-config
      - uuid-dev
      #FireQOS available from 15.04
      #- firehol

  - name: "Clone NetData"
    git:
      accept_hostkey: true
      repo: "https://github.com/firehol/netdata.git"
      dest: "/opt/netdata"
      force: yes
    notify:
      - "Install and configure NetData"
      - "Re-start NetData"

  - name: "Install startup script"
    template:
      src=etc_init_d_netdata
      dest=/etc/init.d/netdata
      owner=root
      group=root
      mode=755
    notify:
      - "Include NetData to Boot-List"
      - "Start NetData"

  - name: "Configure FireQoS"
    template:
      src=etc_fireqos_fireqos.conf
      dest=/etc/fireqos/fireqos.conf
      owner=root
      group=root
      mode=755
    when: false
    notify:
      - "Start FireQoS"

  when: '"netdata" not in excluded_roles'
