---
# file: roles/netdata/tasks/prepare.yml

- name: "Install required packages"
  yum:
    pkg: '{{ item }}'
    state: 'installed'
    update_cache: yes
  with_items:
      - zlib-devel
      - gcc
      - make
      - git
      - autoconf
      - automake
      - pkgconfig
      - libuuid-devel

- name: "Remove existing components"
  file:
    path: '{{ item }}'
    state: 'absent'
  with_items:
    - '/opt/netdata'
    - '/etc/netdata'
    - '/etc/init.d/netdata'
    - '/etc/logrotate.d/netdata'
  when: netdata_force_reset

- name: "Ensure Directory"
  file:
    path: '/etc/netdata/python.d'
    state: 'directory'
