---
# file: roles/netdata/tasks/softnet.yml

- name: "Configure Alert: Softnet"
  replace:
    dest: '/etc/netdata/health.d/softnet.conf'
    regexp: 'warn: \$this > \(\(\$status >= \$WARNING\)  \? \(0\) : \(10\)\)'
    replace: 'warn: $this > (($status >= $WARNING)  ? (0) : (50))'
  notify:
    - "Restart NetData"
