---
# file: roles/netdata/handlers/main.yml

- name: "Include NetData to Boot-List"
  command: update-rc.d netdata defaults

- name: "Restart NetData"
  service:
    name='netdata'
    state='restarted'

- name: "Restart Apache"
  service:
    name='apache2'
    state='restarted'
