---
# file: roles/netdata/handlers/main.yml

- name: "Include NetData to Boot-List"
  command: update-rc.d netdata defaults

- name: "Re-start NetData"
  service:
    name='netdata'
    state='restarted'
