#!/bin/bash
# chkconfig: 345 99 01
# description: startup script

# Source functions
. /lib/lsb/init-functions

DAEMON="netdata"
DAEMON_PATH=/usr/sbin
PIDFILE=/var/run/$DAEMON.pid
DAEMONOPTS="-pidfile $PIDFILE"
STOP_TIMEOUT="10"

service_start()
{
	printf "%-50s" "Starting $DAEMON..."
	start_daemon $DAEMON_PATH/$DAEMON $DAEMONOPTS
	echo
}

service_stop()
{
	printf "%-50s" "Stopping $DAEMON..."
	killproc -p ${PIDFILE} $DAEMON_PATH/$DAEMON
	rm -f ${PIDFILE}
	echo
}

service_status()
{
	status_of_proc -p ${PIDFILE} $DAEMON_PATH/$DAEMON
}

case "$1" in
start)
	service_start
;;
status)
	service_status
;;
stop)
	service_stop
;;
restart)
	service_stop
	service_start
;;
*)
	echo "Usage: $0 {status|start|stop|restart}"
	exit 1
esac
